server:
  port: 8888
  
spring:
  application:
    name: eruka-server
  boot:
    admin:
      context-path: /admin

eureka:
  instance:
    hostname: 192.168.1.11
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
