server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id : services-a
          uri : lb://services-a
          predicates:
            - Path=/services-a/**
          filters:
            - RewritePath=/services-a/(?<path>.*), /$\{path}
        - id: services-b
          uri: lb://services-b
          predicates:
            - Path=/services-b/**
          filters:
            - RewritePath=/services-b/(?<path>.*), /$\{path}

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"