server:
  port: 8090

spring:
  zipkin:
    baseURL: http://localhost:9411/
  sleuth:
    sampler:
      probability: 100
  cloud:
    gateway:
      routes:
        - id: services-a
          uri: lb://services-a
          predicates:
            - Path=/services-a/**
          filters:
            - RewritePath=/services-a/(?<path>.*), /$\{path}

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"