server:
  port: 8090

spring:
  zipkin:
    baseURL: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
    reactor:
      instrumentation-type: MANUAL
  cloud:
    gateway:
      routes:
        - id: services-a
          uri: lb://services-a
          predicates:
            - Path=/services-a/**
          filters:
            - RewritePath=/services-a/(?<path>.*), /$\{path}

logstash:
  host: 192.168.1.11
  port: 5000
  queue-size: 512

logging:
  level:
    com.example.gateway: debug
    
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"