server:
  port: 7070

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

management:
  health:
    binders:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"