server:
  port: 8082

spring:
  mongodb:
    data:
      username: spring
      password: spring
      host: localhost
      port: 27017
      database: SpringMGDB
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"