server:
  port: 8082

spring:
  zipkin:
    baseURL: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
    reactor:
      instrumentation-type: MANUAL
  data:
    mongodb:
      username: spring
      password: spring
      host: localhost
      port: 27017
      database: SpringMGDB

logging:
  level:
    com.example.servicesb: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"