server:
  port: 8081

spring:
  zipkin:
    baseURL: https://192.168.99.100:9411/
  sleuth:
    sampler:
      percentage: 1
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
        
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
