server:
  port: 8082

spring:
  data:
    mongodb:
      username: spring
      password: spring
      host: localhost
      port: 27017
      database: SpringMGDB

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"