server:
  port: 8081

spring:
  zipkin:
    baseURL: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1

logging:
  level:
    com.example.servicesa: debug

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
